-- size of the actual window
WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600

BLOCK_SIZE = 64

MAP_WIDTH = 9 * BLOCK_SIZE
MAP_HEIGHT = 100 * BLOCK_SIZE

CHARACTER_WIDTH = 60
CHARACTER_HEIGHT = 60

PLAYER_WALK_SPEED = 150
PLAYER_JUMP_VELOCITY = -300

GRAVITY = 6

BLOCK_TOTAL = 8
-- block IDs
BLOCK_ID = {
  NULL = 0,
  BLUE = 1,
  GREEN = 2,
  RED = 3,
  YELLOW = 4,
  BROWN = 5,
  WHITH = 6,
  CRYSTAL = 7,
  AIR = 8,
  FLOOR = 9
}
